### ISSUE TITLE
poznamky zo stretnutia so zadavatelom

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/multiexcel-search#1]
spojit pohlady vyvojarov a zadavatelov do jednych poznamok a este ich poslat zadavatelovi s pripadnymi dalsimi otazkami na kontrolu a doplnenie

**Comment by LukasC378** [comment]
[3.10.2022 zápisnica č. 3](https://github.com/TIS2022-FMFI/multiexcel-search/wiki/3.10.2022)
