### ISSUE TITLE
Popis UI dizajnu

### ISSUE THREAD

**Issue by dwwop** [TIS2022-FMFI/multiexcel-search#15]

**Comment by CapitanMikon** [comment]
[AdminUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530775/AdminUserManual.docx)
[AdminUserManual.pdf](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530776/AdminUserManual.pdf)
[BasicUserUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530777/BasicUserUserManual.docx)
[BasicUserUserManual.pdf](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530778/BasicUserUserManual.pdf)

Prve verzie

**Comment by dwwop** [comment]
Zmenit uvodny page
Zmenit font
Clear filters

**Comment by CapitanMikon** [comment]
Zmenit uvodny page -> Done
Zmenit font -> Done
[BasicUserUserManualV2.pdf](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530881/BasicUserUserManualV2.pdf)
[BasicUserUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530882/BasicUserUserManual.docx)
[AdminUserManualV2.pdf](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530883/AdminUserManualV2.pdf)
[AdminUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530884/AdminUserManual.docx)

**Comment by CapitanMikon** [comment]
Font -> uz je times new roman
[AdminUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530899/AdminUserManual.docx)
[BasicUserUserManual.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10530900/BasicUserUserManual.docx)
