### ISSUE TITLE
Špecifikácia vonkajších interfejsov - Excel tabuľky

### ISSUE THREAD

**Issue by dwwop** [TIS2022-FMFI/multiexcel-search#16]

**Comment by CapitanMikon** [comment]
[Špecifikacia vonkajších interfejsov EXCEL.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10095991/Specifikacia.vonkajsich.interfejsov.EXCEL.docx)

**Comment by CapitanMikon** [comment]
[Špecifikacia vonkajších interfejsov EXCEL_V2.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/10095992/Specifikacia.vonkajsich.interfejsov.EXCEL_V2.docx)
