### ISSUE TITLE
Zhotovenie katalógu požiadaviek

### ISSUE THREAD

**Issue by dwwop** [TIS2022-FMFI/multiexcel-search#2]

**Comment by LukasC378** [comment]
[10.10.2022 zápisnica č. 4](https://github.com/TIS2022-FMFI/multiexcel-search/wiki/10.10.2022)

**Comment by pavelpetrovic** [comment]
mojich velmi par komentarov

[Katalog.poziadaviek.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/9754687/Katalog.poziadaviek.docx)

**Comment by pavelpetrovic** [comment]
par komentarov:
 - potesim sa krizovym referenciam v poziadavkach, napr. 3.1.1.b na 3.1.3.?
 - stale mi ale nie je jasne ako sa priority pouziju - sucet? prosim zapisat
 - 3.1.1.C  jeden alebo viac design(ov)
 - otazne veci ako napr. 3.1.1.D - s urcenou odchylkou - mozete vyspecifikovat aj bez odpovedi s tym, ze sa to pripadne zmeni pocas schvalovania ak zadavatel bude pozadovat inak
 - 3.1.1.g ?
 - 3.1.2.f - co sa v historii zobrazuje - ake polia? a do akeho casu? do nekonecna? strankovane?
 - 3.1.2.h - aby bolo zrejme, ze ide iba o pridavanie novych
 - prosim dokoncite KP aj bez odpovedi, podla najlepsej Vasej predstavy, este poslite na poslednu kontrolu, aby na stretnuti so zadavatelom ste uz mohli riesit jeho pripomienky ku KP.

**Comment by CapitanMikon** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2022-FMFI/multiexcel-search/files/9854697/Katalog.poziadaviek.pdf)
Nová verzia

**Comment by pavelpetrovic** [comment]
* veta " Na základe zhody s danou kategóriou a predošlými vyhľadávaniami sa dané výsledky zoradia poďla zadaných priorít. "
neobsahuje informaciu o tom, aky vplyv ma vyber kategorie na usporiadanie v druhom kole
* veta "Kritéria konkrétneho dopytu a zvolené správne výsledky sa uložia" rozdelit na dve vety a vysvetlit ucel:
   kriteria sa ukladaju kvoli prezereniu historie a "zvolene spravne" rozpisat, ze pouzivatel moze oznacit, ktore patria do kategorie, ak tam uz neboli - co s tymi viacerymi - ci naraz vsetky, alebo multiple-select drop box?
* 3.1.1.a  - nie moznost, ale musi sa
* 3.1.1.g - nie je jednoznacne, co sa stane, ak bolo zvolnych viacero kategorii
* 3.1.1.h - upravit: "moze pridat do kategorie"  alebo viacero kategorii naraz?
* 3.1.1.j - potom uz netreba, lebo by to malo byt popisane skor v g,h
* 3.1.1.l - prosim upresnit, co sa exportuje: zoznam tych, ktore oznaci na export
* 3.1.2.f - upresnit ako - napr. na zaklade nejakeho ID dielu?
* prosim namiesto hyperlinkov dat krizove odkazy vo formate "pozri 3.8.17"
* 3.1.2.h - prosim upresnit ako - ci jednotlivo, alebo nejak hromadne, ci v zozname, ale musi zadat nejaky unikatny cas/datum
* 3.1.2.i - prosim uviest, ze ide o inkrementalny import a v obmedzeniach 2.4 uviest, ze system predpoklada, ze importovane excelove subory nie su modifikovane na miestach, ktore uz boli importovane
* 3.1.2. k - m su redundantne, uz je to uvedene v predch. poziadavkach
* 3.1.2. n - o by som presunul hore a asi by som to nenazyval poziadavky rozhrania, lebo to su poziadavky na funkcionalitu
* 3.1.3.b  - nie dielom, ale kriteriam
* 3.1.4.b,c - prosim upresnit, co znamena filtrovat a ci aj nejake usporiadanie
* 3.1.4.d - zasa vyskocilo oznacenie, treba to domysliet a dotiahnut

podla tohto to prosim upravte, ak to bude konzistentne, tak uz ten dokument pouzite ako zaklad pre vyjednavanie so zadavatelom... 
ja ho ale este raz budem chciet "skompilovat" - idealne do stvrtka...

**Comment by dwwop** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/9864273/Katalog.poziadaviek.docx)

Nová verzia

**Comment by pavelpetrovic** [comment]
parada. za mna potlesk. som zvedavy, co na ten nas vynalez s menenim kategorie povedia. este mi napadlo, ze ked prezera historiu vyhladavania, ci by nechcel jednym klikom niektore vyhladanie z historie zopakovat, aby ho nemusel rucne naklikavat, aby videl, ake vysledky to vtedy dalo...

ak chcete tak su tam este take tie "Pri každom dieli " => diele, "použivateľom" - dlzen, "zadávanie kritérii " - dlzen na konci, aj 2X, aj Vam to word podciarkuje.

**Comment by dwwop** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2022-FMFI/multiexcel-search/files/9903929/Katalog.poziadaviek.docx)

**Comment by pavelpetrovic** [comment]
okrem dvoch koncoviek vsetko vyzera dokonalo, prosim dat schvalit zadavatelovi.

**Comment by dwwop** [comment]
https://docs.google.com/document/d/1IVB-Dsf26nVrGwu5S0dtP3TkRLbyMF4DHSkANJg49H4/edit#
