### ISSUE TITLE
Návrh UI dizajnu

### ISSUE THREAD

**Issue by CapitanMikon** [TIS2022-FMFI/multiexcel-search#3]
vytvorenie pouzivatelskeho rozhrania

**Comment by kyska11** [comment]
![Tis](https://user-images.githubusercontent.com/100410828/200549445-d8f9a5b7-ec30-4987-9a33-d8d834e6beb4.png)

Prvotný navrh GUI.

**Comment by kyska11** [comment]
https://www.figma.com/file/2IJ9b1NxWOp3xp5lLWmNt6/GUI-DESKOP-APLIKACIE?node-id=0%3A1

Hotová verzia vo figme.
Komentovat je možné priamo vo figme jednotlivé komponenty.
