### ISSUE TITLE
Backend - Správa dát dielov

### ISSUE THREAD

**Issue by dwwop** [TIS2022-FMFI/multiexcel-search#39]

**Comment by LukasC378** [comment]
- pridanie a odstranenie kategorii dielu
- pridanie ratingu - na vstupe list dielov
- dostanem query vratim zoznam dielov

**Comment by dwwop** [comment]
- Prva faza vyhladavania -> dostane ranges parametrov a zoznam nazvov, a priority parametrov kategorii
                                        -> implementuje strankovanie
- Druha faza vyhladavanie -> zoradenie podla zhody s kategoriami
                                          -> sekundarne zoradenie bud podla rating alebo podla priorit z prvej fazy vyhladavania
