### ISSUE TITLE
Zhotovenie návrhu systému

### ISSUE THREAD

**Issue by CapitanMikon** [TIS2022-FMFI/multiexcel-search#4]

**Comment by CapitanMikon** [comment]
![FlowDiagram](https://user-images.githubusercontent.com/77883550/197607347-f5bacb2c-f6ea-4f91-aed2-397f76cba10f.svg)

**Comment by dwwop** [comment]
https://docs.google.com/document/d/15IfNw7f3jBvemaSFVJRmk4uv0cS91bB7LlBBEZ9OGso/edit?usp=sharing
