### ISSUE TITLE
vytvorenie stavového diagramu

### ISSUE THREAD

**Issue by CapitanMikon** [TIS2022-FMFI/multiexcel-search#8]

**Comment by CapitanMikon** [comment]
![StateDiagram](https://user-images.githubusercontent.com/77883550/198338888-744ddcc0-5f68-4243-9da5-7826d37ef802.svg)

**Comment by dwwop** [comment]
Zmeniť submit a export výsledkov podľa GUI
Upraviť na iba vyhľadávanie

**Comment by CapitanMikon** [comment]
zmenil som kompletne stavovy diagram na inu entitu (aby to nebolo gui)
![obrázok](https://user-images.githubusercontent.com/77883550/201734178-fc847dad-2893-4021-ab91-98a0726a4965.png)
