### ISSUE TITLE
vytvorenie component diagramu

### ISSUE THREAD

**Issue by CapitanMikon** [TIS2022-FMFI/multiexcel-search#9]

**Comment by dwwop** [comment]
https://drive.google.com/drive/folders/1N51jiumSKU4VtMIDBP_WMm0BUbg7BPBU?usp=sharing

**Comment by dwwop** [comment]
![Image](https://user-images.githubusercontent.com/99904993/202926271-fdc3df8b-b11d-4197-8e11-9fc95faef50d.jpg)

**Comment by dwwop** [comment]
![Image](https://user-images.githubusercontent.com/99904993/203778628-b117f22f-6ffa-4d2c-9ca1-601bdffaa41b.jpg)
